api_version = "2024-10"

[[extensions]]
uid = "2417e01d-2144-b7f8-7466-0fea647170d893f038bf"
type = "ui_extension"
name = "Checkout API Demo"
handle = "checkout-api-demo"

[extensions.capabilities]
network_access = true
read_shipping = true
read_products = true

[[extensions.targeting]]
module = "./src/Checkout.jsx"
target = "purchase.checkout.block.render"
