api_version = "2025-01"

[[extensions]]
uid = "2417e01d-2144-b7f8-7466-0fea647170d893f038bf"
type = "ui_extension"
name = "Checkout API Demo"
handle = "checkout-api-demo"

[extensions.capabilities]
network_access = true
read_shipping = true
read_products = true
api_access = true
write_cart_metafields = true

[[extensions.targeting]]
module = "./src/CheckoutWithServiceability.jsx"
target = "purchase.checkout.block.render"

# Define metafields that this extension can write
[[extensions.metafields]]
namespace = "custom"
key = "serviceability_data"
type = "json"
